/* (C) 2026 
bidder.app */
package com.bidder.service.models;

public enum AuctionCategory {
	ELECTRONICS, VEHICLES, REAL_ESTATE, ART_AND_COLLECTIBLES, JEWELLERY_AND_WATCHES, FASHION_AND_ACCESSORIES, FURNITURE_AND_HOME, SPORTS_AND_OUTDOORS, BOOKS_AND_MEDIA, TOYS_AND_GAMES, INDUSTRIAL_AND_MACHINERY, ANTIQUES, OTHER
}
